### PR TITLE
Mount current repository on CoreOS VM

### PR DESCRIPTION
**Pull request by dtan4**
## WHY

To develop application on CoreOS VM
## WHAT

Mount current repository on CoreOS VM with repository name

``` bash
$ vagrant ssh
CoreOS beta (766.1.0)
core@core-01 ~ $ ls
boilerplate
core@core-01 ~ $ ls boilerplate/
Dockerfile  README.md  coreos  doc  script
```

### CODE REVIEW

**Comment by awakia** [comment]
I'm not sure repository name e.g. `boilerplate` is good or not. How do you think? I think `shared` or `synced_folder` may be better.

cc: @koudaiii

**Comment by koudaiii** [comment]
synced_folder :+1:

**Comment by dtan4** [comment]
``` bash
$ vagrant ssh
CoreOS beta (766.1.0)
core@core-01 ~ $ ls
synced_folder
core@core-01 ~ $ ls synced_folder/
Dockerfile  README.md  coreos  doc  script
```

**Comment by awakia** [comment]
Thank you!!

**Pull request merged**
